### PR TITLE
Add a writer_kwargs argument to MDAReporter and speed up testing

### LINKED ISSUE #6: MDAReporter, when reporting H5MD, has no way to leave the forces or velocities out
## Is your feature request related to a problem? ##
Forces and velocities are space intensive and not always needed. There should be a way to pass `force=False` and `velocity=False` to the `H5MDWriter` when writing out H5MD files.

### PR DESCRIPTION
**Pull request by orionarcher**
Fixes #6 

Changes made in this Pull Request:

 - format code with Black
 - added a writer_kwargs argument to MDAReporter that is passed to mda.Writer
 - migrate testing to use serialized simulation instead of re-instantiating each time. Much faster, all tests pass locally.

PR Checklist
------------
 - [x] Tests?
 - [x] Docs?
 - [x] CHANGELOG updated?
 - [x] Issue raised/referenced?

### CODE REVIEW

**Comment by orionarcher** [comment]
Would love a look from @richardjgowers or @sef43 when y'all have time! I think the changes are pretty innocuous and would help me solve a downstream use case.

**Comment by sef43** [comment]
Thanks for the contribution!, can this please be re-done without the formatting changes please? The formating change should be a seperate PR.

**Comment by orionarcher** [comment]
Are you opened to the formatting changes? I opened a PR #8 with just the Black formatting. 

If possible, I'd like to merge that and then reopen this PR so I don't have to sort out the logic from formatting changes. (A little lazy I admit.)

**Comment by sef43** [comment]
Currently yes I am against the formatting changes to any of the existing files. The current formatting follows the openmm formatting for Reporter classes. There is no reason to deviate from this. 

> I don't have to sort out the logic from formatting changes. 

As you point out here the key issue is that the unnecessary formatting changes obscure the functional changes to the code. I think MDAnalysis does not allow black formatting of existing code, only new code, for this reason. 
https://github.com/MDAnalysis/mdanalysis/issues/2450

**Comment by orionarcher** [comment]
Fair enough, I understand the desire to avoid black and stay compatible with upstream formatting. 

I added a new PR #9 that implements the testing and kwargs changes without the black formatting.

**Pull request closed without merging**
